### ISSUE TITLE
[GLITCH/BUG] Screen freezes at random time when opening presents

### ISSUE THREAD

**Issue by ez-bake** [Geokureli/Advent2020#3]
It happens randomly, but going up to any present and opening it, sometime the screen freezes completely.  I can't move the mouse in-game, the music keeps going and the page is working fine, but I've waited for five minutes and nothing happened.  Only when I refresh the page can I see the images again.  I repeat: it happens randomly to any present.  I don't know if I'm impatient and the game just needs to load it, or if this is a bug.

#### Date issue happened on: December 5, 2020  Location: California, USA

**Comment by Geokureli** [comment]
some images take a bit to finish loading, these images are HUUGE. if it happens again try pressing Cntl + Shift + i and looking for errors in the console
